# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e929df269c377e24b30cdc573d7148251f648692d7aafcc0522b08ce792a84310fdb2789d88f558fdc5d9ac655f6d885528834dab030920549af991fe94965b

test:
  secret_key_base: 1be8e3c8232795943c705afcf29301e7e4b43d256f04dad0aabd1790919b63e80784ee1fa1deab8c2600d46e462785f11ef9f3f41a6baa759729ca17ccab66f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
